-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS core.items
(
    id bigserial NOT NULL,
    sn character varying(512) COLLATE pg_catalog."default" NOT NULL,
    hash_genesis bytea NOT NULL,
    status core.e_item_status NOT NULL DEFAULT 'CREATED',
    title character varying(256) COLLATE pg_catalog."default" NOT NULL,
    stamp core.t_created_updated NOT NULL DEFAULT (now(), now()),
    creator_id bigint NOT NULL,
    ledger_head bigint,
    CONSTRAINT pk_items_id PRIMARY KEY (id),
    CONSTRAINT uq_items_sn UNIQUE (sn),
    CONSTRAINT uq_items_ledger_head UNIQUE (ledger_head)
);

CREATE TABLE IF NOT EXISTS core.users
(
    id bigserial NOT NULL,
    login character varying(99) NOT NULL,
    password character varying(512) NOT NULL,
    status core.e_user_status NOT NULL DEFAULT 'PENDING',
    data_hash bytea NOT NULL,
    stamp core.t_created_updated NOT NULL DEFAULT (now(), now()),
    CONSTRAINT pk_users_id PRIMARY KEY (id),
    CONSTRAINT uq_users_login UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS audit.item_ledger
(
    id bigserial NOT NULL,
    prev_id bigint,
    version smallint NOT NULL DEFAULT 1,
    hash bytea NOT NULL,
    event_type audit.e_item_event_type NOT NULL,
    event_hash bytea NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    item_id bigint NOT NULL,
    creator_id bigint NOT NULL,
    CONSTRAINT "pk_IL_id" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS data.user_details
(
    user_id bigint NOT NULL,
    email character varying(256) NOT NULL,
    name character varying(64) NOT NULL,
    surname character varying(128) NOT NULL,
    CONSTRAINT "pk_UD_user_id" PRIMARY KEY (user_id),
    CONSTRAINT uq_user_details_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS data.offers
(
    id bigserial NOT NULL,
    status data.e_offer_status NOT NULL DEFAULT 'ACTIVE',
    price money NOT NULL,
    description text,
    stamp core.t_created_updated NOT NULL DEFAULT (now(), now()),
    item_id bigint NOT NULL,
    creator_id bigint NOT NULL,
    CONSTRAINT pk_offers_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS data.bids
(
    id bigserial NOT NULL,
    value money NOT NULL,
    status data.e_bid_status NOT NULL DEFAULT 'PENDING',
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    offer_id bigint NOT NULL,
    bidder_id bigint NOT NULL,
    CONSTRAINT pk_bids_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS data.conversations
(
    id bigserial NOT NULL,
    subject character varying(256),
    contents text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    commenter_id bigint NOT NULL,
    offer_id bigint NOT NULL,
    bid_id bigint,
    CONSTRAINT pk_conversations_id PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS core.items
    ADD CONSTRAINT fk_items_user_id FOREIGN KEY (creator_id)
    REFERENCES core.users (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS core.items
    ADD CONSTRAINT fk_items_ledger_head FOREIGN KEY (ledger_head)
    REFERENCES audit.item_ledger (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS audit.item_ledger
    ADD CONSTRAINT "fk_IL_self_id" FOREIGN KEY (prev_id)
    REFERENCES audit.item_ledger (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS audit.item_ledger
    ADD CONSTRAINT "fk_IL_user_id" FOREIGN KEY (creator_id)
    REFERENCES core.users (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS audit.item_ledger
    ADD CONSTRAINT "fk_IL_item_id" FOREIGN KEY (item_id)
    REFERENCES core.items (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS data.user_details
    ADD CONSTRAINT "fk_UD_user_id" FOREIGN KEY (user_id)
    REFERENCES core.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS data.offers
    ADD CONSTRAINT fk_offers_creator_id FOREIGN KEY (creator_id)
    REFERENCES core.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS data.offers
    ADD CONSTRAINT fk_offers_item_id FOREIGN KEY (item_id)
    REFERENCES core.items (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS data.bids
    ADD CONSTRAINT fk_bids_offer_id FOREIGN KEY (offer_id)
    REFERENCES data.offers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS data.bids
    ADD CONSTRAINT fk_bids_bidder_id FOREIGN KEY (bidder_id)
    REFERENCES core.users (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS data.conversations
    ADD CONSTRAINT fk_conversations_offer_id FOREIGN KEY (offer_id)
    REFERENCES data.offers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS data.conversations
    ADD CONSTRAINT fk_conversations_bid_id FOREIGN KEY (bid_id)
    REFERENCES data.bids (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS data.conversations
    ADD CONSTRAINT fk_conversations_commenter_id FOREIGN KEY (commenter_id)
    REFERENCES core.users (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;

END;
