FROM docker.io/golang:1.26-alpine AS builder
RUN apk add --no-cache git
RUN go install go.k6.io/xk6/cmd/xk6@latest
RUN xk6 build \
    --with github.com/grafana/xk6-sql@latest \
    --with github.com/grafana/xk6-sql-driver-postgres@latest \
    --output /k6

FROM docker.io/alpine:latest
COPY --from=builder /k6 /usr/local/bin/k6
ENTRYPOINT ["k6"]
