#!/bin/bash
set -euo pipefail

VERSION='2.1'
EXTENSION='sql'
VERBOSE=1
DRY_RUN=0

show_help() {
    echo "Usage: $0 [TARGET_DIR] [OUT_DIR] [-v|-vv|-q|-n|-h]"
    echo
    echo "Options:"
    echo "  -v, --version   Show version"
    echo "  -q, --quiet     Quiet"
    echo "  -vv             Very verbose output"
    echo "  -n, --dry-run   Show inclusion order without writing files"
    echo "  -h, --help      Show this help message"
    echo
    echo "TARGET_DIR defaults to 'db'"
    echo "OUT_DIR   defaults to 'gen'"
    echo
    echo "Assembly strategy:"
    echo "  CREATE.gen.sql:"
    echo "    1) extensions (global + per-schema)"
    echo "    2) per-stage assembly by schema order: core -> audit -> data"
    echo "       stages: types, _ERD (root file), constraints, functions, triggers"
    echo "  DROP.gen.sql:"
    echo "    reversed schema order: data -> audit -> core"
    echo "    uses each schema DROP.sql if present"
}

log() {
    # $1 = level (0 quiet, 1 normal, 2 verbose)
    # $2.. = message
    local level=$1
    shift
    if [ "${VERBOSE}" -ge "${level}" ]; then
        echo "$@"
    fi
}

upper() {
    echo "$1" | tr '[:lower:]' '[:upper:]'
}

emit() {
    # $1 = out_file
    # $2.. = lines to append
    local out_file=$1
    shift

    if [ "${DRY_RUN}" -eq 1 ]; then
        log 1 "DRY RUN: append to $out_file"
        return
    fi

    printf "%s\n" "$@" >> "$out_file"
}

append_file_with_header() {
    # $1 out_file
    # $2 title
    # $3 file_path
    local out_file=$1
    local title=$2
    local file_path=$3

    if [ -f "$file_path" ]; then
        log 2 "  + Including $file_path"
        if [ "${DRY_RUN}" -eq 1 ]; then
            log 1 "DRY RUN: include $file_path -> $out_file"
            return
        fi
        {
            echo ""
            echo "-- $title --"
            cat "$file_path"
        } >> "$out_file"
    else
        log 2 "  - Missing $file_path (skipped)"
    fi
}

append_schema_stage() {
    # $1 out_file
    # $2 target_dir
    # $3 schema
    # $4 stage_filename
    local out_file=$1
    local target_dir=$2
    local schema=$3
    local stage=$4

    local path="$target_dir/$schema/$stage"
    if [ -f "$path" ]; then
        append_file_with_header "$out_file" "$(upper "$schema") :: $stage" "$path"
    else
        log 2 "  - Missing $path (skipped)"
    fi
}

# Parse options first
while [[ "${1:-}" == -* ]]; do
    case "$1" in
        -vv)
            VERBOSE=2
            shift
            ;;
        -q|--quiet)
            VERBOSE=0
            shift
            ;;
        -n|--dry-run)
            DRY_RUN=1
            shift
            ;;
        -v|--version)
            echo "$0 version $VERSION"
            exit 0
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Positional args
target_dir=${1:-db}
out_dir=${2:-gen}

SCHEMAS_CREATE=(core audit data)
SCHEMAS_DROP=(data audit core)
STAGES=("types.$EXTENSION" "_ERD.$EXTENSION" "constraints.$EXTENSION" "functions.$EXTENSION" "triggers.$EXTENSION")

CREATE_FILE="$out_dir/CREATE.gen.$EXTENSION"
DROP_FILE="$out_dir/DROP.gen.$EXTENSION"
TRUNCATE_FILE="$out_dir/TRUNCATE.gen.$EXTENSION"
TEST_FILE="$out_dir/TEST.gen.$EXTENSION"

if [ "${DRY_RUN}" -eq 1 ]; then
    log 1 "DRY RUN: no files will be written"
else
    log 1 "Ensuring output directory exists: $out_dir"
    mkdir -p "$out_dir"
    rm -f "$CREATE_FILE" "$DROP_FILE" "$TRUNCATE_FILE" "$TEST_FILE"
fi

# ---------------------------
# CREATE.sql (ordered build)
# ---------------------------
log 1 "Building $CREATE_FILE"

emit "$CREATE_FILE" \
    "-- Auto-generated by tools/compose-sql.sh v$VERSION" \
    "-- CREATE order: core -> audit -> data" \
    "-- Stage order: extensions -> types -> _ERD -> constraints -> functions -> triggers"

# 1) global/root extensions first
append_file_with_header "$CREATE_FILE" "GLOBAL :: extensions.$EXTENSION" "$target_dir/extensions.$EXTENSION"

# 2) per-schema extensions next (still before other stages)
for schema in "${SCHEMAS_CREATE[@]}"; do
    schema_dir="$target_dir/$schema"
    if [ ! -d "$schema_dir" ]; then
        log 1 "WARNING: schema directory missing: $schema_dir"
        continue
    fi

    emit "$CREATE_FILE" "" "" "-- - $(upper "$schema") - --" "CREATE SCHEMA IF NOT EXISTS \"$schema\";"

    append_schema_stage "$CREATE_FILE" "$target_dir" "$schema" "extensions.$EXTENSION"
done

# 3) staged assembly across all schemas in requested order
for stage in "${STAGES[@]}"; do
    log 2 "Stage: $stage"

    if [ "$stage" == "_ERD.$EXTENSION" ]; then
        # Root ERD file inserted once at ERD stage
        append_file_with_header "$CREATE_FILE" "GLOBAL :: _ERD.$EXTENSION" "$target_dir/_ERD.$EXTENSION"
        continue
    fi

    for schema in "${SCHEMAS_CREATE[@]}"; do
        schema_dir="$target_dir/$schema"
        if [ ! -d "$schema_dir" ]; then
            continue
        fi
        append_schema_stage "$CREATE_FILE" "$target_dir" "$schema" "$stage"
    done
done

# ---------------------------
# DROP.sql (reversed order)
# ---------------------------
log 1 "Building $DROP_FILE"

emit "$DROP_FILE" \
    "-- Auto-generated by tools/compose-sql.sh v$VERSION" \
    "-- DROP order: data -> audit -> core (reverse of CREATE schema order)"

for schema in "${SCHEMAS_DROP[@]}"; do
    schema_dir="$target_dir/$schema"
    if [ ! -d "$schema_dir" ]; then
        log 1 "WARNING: schema directory missing: $schema_dir"
        continue
    fi

    append_file_with_header "$DROP_FILE" "$(upper "$schema") :: DROP.$EXTENSION" "$schema_dir/DROP.$EXTENSION"
done

# ---------------------------
# TRUNCATE.sql + TEST.sql
# Keep practical order:
#   TRUNCATE reverse (like DROP)
#   TEST create order
# ---------------------------
log 1 "Building $TRUNCATE_FILE"
emit "$TRUNCATE_FILE" \
    "-- Auto-generated by tools/compose-sql.sh v$VERSION" \
    "-- TRUNCATE order: data -> audit -> core"

for schema in "${SCHEMAS_DROP[@]}"; do
    schema_dir="$target_dir/$schema"
    [ -d "$schema_dir" ] || continue
    append_file_with_header "$TRUNCATE_FILE" "$(upper "$schema") :: TRUNCATE.$EXTENSION" "$schema_dir/TRUNCATE.$EXTENSION"
done

log 1 "Building $TEST_FILE"
emit "$TEST_FILE" \
    "-- Auto-generated by tools/compose-sql.sh v$VERSION" \
    "-- TEST order: core -> audit -> data"

for schema in "${SCHEMAS_CREATE[@]}"; do
    schema_dir="$target_dir/$schema"
    [ -d "$schema_dir" ] || continue
    append_file_with_header "$TEST_FILE" "$(upper "$schema") :: TEST.$EXTENSION" "$schema_dir/TEST.$EXTENSION"
done

log 1 "Done."
log 1 "Generated:"
log 1 "  $CREATE_FILE"
log 1 "  $DROP_FILE"
log 1 "  $TRUNCATE_FILE"
log 1 "  $TEST_FILE"
